"""Add plan relationship and unify Base

Revision ID: 09d2a3005c4d
Revises: 8f85a068986d
Create Date: 2026-06-16 12:19:28.595965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d2a3005c4d'
down_revision: Union[str, None] = '8f85a068986d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
