"""Initial migration

Revision ID: 8f85a068986d
Revises: 
Create Date: 2026-06-13 21:24:18.393168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f85a068986d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_downloads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('original_url', sa.String(length=2048), nullable=False),
    sa.Column('normalized_url', sa.String(length=2048), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('uploader', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cd_access', 'cached_downloads', ['access_count'], unique=False)
    op.create_index('idx_cd_expires', 'cached_downloads', ['expires_at'], unique=False)
    op.create_index('idx_cd_last_access', 'cached_downloads', ['last_accessed'], unique=False)
    op.create_index('idx_cd_platform', 'cached_downloads', ['platform'], unique=False)
    op.create_index('idx_cd_url_hash', 'cached_downloads', ['url_hash'], unique=True)
    op.create_index(op.f('ix_cached_downloads_platform'), 'cached_downloads', ['platform'], unique=False)
    op.create_index(op.f('ix_cached_downloads_url_hash'), 'cached_downloads', ['url_hash'], unique=True)
    op.create_table('cached_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=256), nullable=False),
    sa.Column('url_hash', sa.String(length=256), nullable=True),
    sa.Column('format_id', sa.String(length=50), nullable=True),
    sa.Column('codec', sa.String(length=50), nullable=True),
    sa.Column('telegram_file_id', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('video_id', sa.String(length=255), nullable=True),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash', 'format_id', 'codec', name='uq_cached_files_lookup')
    )
    op.create_index(op.f('ix_cached_files_created_at'), 'cached_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_cached_files_file_hash'), 'cached_files', ['file_hash'], unique=False)
    op.create_index(op.f('ix_cached_files_id'), 'cached_files', ['id'], unique=False)
    op.create_index(op.f('ix_cached_files_platform'), 'cached_files', ['platform'], unique=False)
    op.create_index('ix_cached_files_platform_video', 'cached_files', ['platform', 'video_id'], unique=False)
    op.create_index(op.f('ix_cached_files_telegram_file_id'), 'cached_files', ['telegram_file_id'], unique=False)
    op.create_index('ix_cached_files_telegram_id', 'cached_files', ['telegram_file_id'], unique=False)
    op.create_index(op.f('ix_cached_files_url_hash'), 'cached_files', ['url_hash'], unique=False)
    op.create_index(op.f('ix_cached_files_video_id'), 'cached_files', ['video_id'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_username', sa.String(length=255), nullable=True),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('invite_link', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_channel_id'), 'channels', ['channel_id'], unique=True)
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.create_index(op.f('ix_channels_is_active'), 'channels', ['is_active'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monthly_price', sa.Float(), nullable=False),
    sa.Column('yearly_price', sa.Float(), nullable=True),
    sa.Column('download_limit', sa.Integer(), nullable=True),
    sa.Column('max_file_size', sa.Integer(), nullable=True),
    sa.Column('quality_limit', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_is_active'), 'plans', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('preferred_quality', sa.String(length=50), nullable=True),
    sa.Column('total_downloads', sa.Integer(), nullable=True),
    sa.Column('total_coins', sa.Float(), nullable=True),
    sa.Column('total_spent', sa.Float(), nullable=True),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('referred_by', sa.BigInteger(), nullable=True),
    sa.Column('referral_count', sa.Integer(), nullable=True),
    sa.Column('referral_milestone', sa.Integer(), nullable=True),
    sa.Column('referral_badge', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)
    op.create_index(op.f('ix_users_is_blocked'), 'users', ['is_blocked'], unique=False)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_users_referred_by'), 'users', ['referred_by'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_telegram_username'), 'users', ['telegram_username'], unique=False)
    op.create_table('cached_qualities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cache_id', sa.Integer(), nullable=False),
    sa.Column('quality_label', sa.String(length=100), nullable=False),
    sa.Column('format_id', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('extension', sa.String(length=10), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('telegram_file_id', sa.String(length=255), nullable=False),
    sa.Column('telegram_file_unique_id', sa.String(length=100), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('video_codec', sa.String(length=50), nullable=True),
    sa.Column('audio_codec', sa.String(length=50), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('last_downloaded', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cache_id'], ['cached_downloads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cq_cache_id', 'cached_qualities', ['cache_id'], unique=False)
    op.create_index('idx_cq_file_id', 'cached_qualities', ['telegram_file_id'], unique=False)
    op.create_index('idx_cq_quality_label', 'cached_qualities', ['quality_label'], unique=False)
    op.create_index(op.f('ix_cached_qualities_cache_id'), 'cached_qualities', ['cache_id'], unique=False)
    op.create_index(op.f('ix_cached_qualities_telegram_file_id'), 'cached_qualities', ['telegram_file_id'], unique=True)
    op.create_table('coin_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coin_transactions_created_at'), 'coin_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_coin_transactions_id'), 'coin_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_coin_transactions_user_id'), 'coin_transactions', ['user_id'], unique=False)
    op.create_table('downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('module_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=100), nullable=True),
    sa.Column('quality', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downloads_created_at'), 'downloads', ['created_at'], unique=False)
    op.create_index(op.f('ix_downloads_id'), 'downloads', ['id'], unique=False)
    op.create_index(op.f('ix_downloads_user_id'), 'downloads', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reward_coins', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_created_at'), 'referrals', ['created_at'], unique=False)
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.create_index(op.f('ix_referrals_referred_user_id'), 'referrals', ['referred_user_id'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_is_active'), 'subscriptions', ['is_active'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_is_active'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_user_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_created_at'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_downloads_user_id'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_id'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_created_at'), table_name='downloads')
    op.drop_table('downloads')
    op.drop_index(op.f('ix_coin_transactions_user_id'), table_name='coin_transactions')
    op.drop_index(op.f('ix_coin_transactions_id'), table_name='coin_transactions')
    op.drop_index(op.f('ix_coin_transactions_created_at'), table_name='coin_transactions')
    op.drop_table('coin_transactions')
    op.drop_index(op.f('ix_cached_qualities_telegram_file_id'), table_name='cached_qualities')
    op.drop_index(op.f('ix_cached_qualities_cache_id'), table_name='cached_qualities')
    op.drop_index('idx_cq_quality_label', table_name='cached_qualities')
    op.drop_index('idx_cq_file_id', table_name='cached_qualities')
    op.drop_index('idx_cq_cache_id', table_name='cached_qualities')
    op.drop_table('cached_qualities')
    op.drop_index(op.f('ix_users_telegram_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_referred_by'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_is_blocked'), table_name='users')
    op.drop_index(op.f('ix_users_is_admin'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_plans_is_active'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_channels_is_active'), table_name='channels')
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_channel_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_cached_files_video_id'), table_name='cached_files')
    op.drop_index(op.f('ix_cached_files_url_hash'), table_name='cached_files')
    op.drop_index('ix_cached_files_telegram_id', table_name='cached_files')
    op.drop_index(op.f('ix_cached_files_telegram_file_id'), table_name='cached_files')
    op.drop_index('ix_cached_files_platform_video', table_name='cached_files')
    op.drop_index(op.f('ix_cached_files_platform'), table_name='cached_files')
    op.drop_index(op.f('ix_cached_files_id'), table_name='cached_files')
    op.drop_index(op.f('ix_cached_files_file_hash'), table_name='cached_files')
    op.drop_index(op.f('ix_cached_files_created_at'), table_name='cached_files')
    op.drop_table('cached_files')
    op.drop_index(op.f('ix_cached_downloads_url_hash'), table_name='cached_downloads')
    op.drop_index(op.f('ix_cached_downloads_platform'), table_name='cached_downloads')
    op.drop_index('idx_cd_url_hash', table_name='cached_downloads')
    op.drop_index('idx_cd_platform', table_name='cached_downloads')
    op.drop_index('idx_cd_last_access', table_name='cached_downloads')
    op.drop_index('idx_cd_expires', table_name='cached_downloads')
    op.drop_index('idx_cd_access', table_name='cached_downloads')
    op.drop_table('cached_downloads')
    # ### end Alembic commands ###
